image: java:8-jdk

stages:
  - build
#  - deploy
# - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export MYSQL_URL=$db
  - export MYSQL_USERNAME=$user
  - export MYSQL_PASSWORD=$password
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - echo MYSQL_URL
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

#test:
#  stage: test
#  script:
#    - ./gradlew check

#deploy:
#  stage: deploy
#  script:
#    - ./gradlew bootRun

after_script:
  - echo "End CI"
