image: java:8-jdk

stages:
  - test
  - build
# - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export MYSQL_URL=$DB_URL
  - export MYSQL_USERNAME=$DB_USER
  - export MYSQL_PASSWORD=$DB_PASSWORD
  - echo $MYSQL_URL
  - echo {$DB_URL}
  - echo $DB_URL
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week


test:
  stage: test
  script:
    - ./gradlew check

#deploy:
#  stage: deploy
#  script:
#    - ./script

after_script:
  - echo "End CI"
