image: java:8-jdk

stages:
  - test
  - build

before_script:
  - echo "Continuous Integration Starting"
  - export MYSQL_URL=$DB_URL
  - export MYSQL_USERNAME=$DB_USER
  - export MYSQL_PASSWORD=$DB_PASSWORD
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
  only:
    - master

after_script:
  - echo "Continuous Integration Ending"
